export const CALLBACK_AZUREAD_URL = '/auth/azuread/callback'
export const AZUREAD_LOGIN_URL = '/auth/azuread'
// export const AZUREAD_LOGIN_WEB_URL = '/auth/azuread-web'
export const FAILURE_LOGIN_URL = '/login?invalid=1'
export const SCOPE = 'user.read openid profile email'
