import React from 'react'
import { observer, useSession, useDoc } from 'startupjs'
import { Span, Avatar, Layout, Content, Div } from '@startupjs/ui'
import { LogoutButton } from '@startupjs/auth'
import './index.styl'
import './test1'
import './test2'
import './test3'
import './test4'
import './test5'
import './test6'
import './test7'
import './test8'
import './test9'
import './test10'
import './test11'
import './test12'
import './test13'
import './test15'
import './test16'
import './test17'
import './test18'
import './test19'
import './test20'
import './test21'
import './test22'
import './test23'
import './test24'
import './test25'
import './test26'
import './test27'
import './test28'
import './test29'
import './test30'
import './test31'
import './test32'
import './test33'
import './test34'
import './test35'
import './test36'
import './test37'
import './test38'
import './test39'
import './test40'
import './test41'
import './test42'
import './test43'
import './test44'
import './test45'
import './test46'
import './test47'
import './test48'
import './test49'
import './test50'
import './test51'
import './test52'
import './test53'
import './test54'
import './test55'
import './test56'
import './test57'
import './test58'
import './test59'
import './test60'
import './test61'
import './test62'
import './test63'
import './test64'
import './test65'
import './test66'
import './test67'
import './test68'
import './test69'
import './test70'
import './test71'
import './test72'
import './test73'
import './test74'
import './test75'
import './test76'
import './test77'
import './test78'
import './test79'
import './test80'
import './test81'
import './test82'
import './test83'
import './test84'
import './test85'
import './test86'
import './test87'
import './test88'
import './test89'
import './test90'
import './test91'
import './test92'
import './test93'
import './test94'
import './test95'
import './test96'
import './test97'
import './test98'
import './test99'
import './test100'

export default observer(function PProfile () {
  const [userId] = useSession('userId')
  const [user] = useDoc('users', userId)

  if (!user) return null

  return pug`
    Layout
      Content
        Div.root
          Avatar(
            size='xxl'
            src=user.avatarUrl
          )
          Div.info
            Span.line(bold)= user.firstName + ' ' + user.lastName
            Span.line= user.email
          LogoutButton
  `
})
