export const ACCESS_ERROR_CODES = {
  ERR_ACCESS_ONLY_SERVER_AGGREATE: 'ERR_ACCESS_DENY_CREATE',
  ERR_ACCESS_NO_SERVER_AGGREGATE_NAME: 'ERR_ACCESS_DENY_READ',
  ERR_ACCESS_IN_SERVER_QUERY: 'ERR_ACCESS_IN_SERVER_QUERY'
}
