// This file is generated by TeamPlay. Do not edit manually.
/* eslint-disable */
import 'teamplay'

type __TeamplayFeatures = {}

declare module 'teamplay' {
  interface TeamplayFeatures extends __TeamplayFeatures {}
}
