apiVersion: v1
kind: Service
metadata:
  name: ${_APP}
  labels:
    app: ${_APP}
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"${_APP}"}}'
spec:
  type: NodePort
  selector:
    app: ${_APP}
  ports:
  - name: http
    port: 80
    targetPort: 3000
