export const AUTH_URL = '/auth'
export const AUTH_TOKEN_KEY = '__successAuthToken__'
export const AUTH_GET_URL = `${AUTH_URL}/getUrl`
export const AUTH_FINISH_URL = `${AUTH_URL}/finish`
export const AUTH_PLUGIN_NAME = 'auth'
export const AUTH_LOCAL_PROVIDER = 'local'
export const AUTH_FORCE_PROVIDER = 'force'
export const AUTH_2FA_PROVIDER = '2fa'
export const DEFAULT_ENABLED_PROVIDER_IDS = ['google', 'apple', 'github', 'local', '2fa', 'force']
