// This file is generated by TeamPlay. Do not edit manually.
/* eslint-disable */
import { type CollectionsFromManifest, type FromJsonSchema, type PathModelsFromManifest, type SignalChild } from 'teamplay'
import type __CollectionModel0 from "./model/auths.js"
import type __CollectionModel1 from "./model/files.js"
import type __PathModel2 from "./model/secrets.[id].js"
import type __CollectionModel3 from "./model/secrets.js"
import type __PathModel4 from "./model/testCounts.[id].ts"
import type __CollectionModel5 from "./model/testCounts.js"
import type __Schema6 from "./model/testCounts.schema.js"
import type __CollectionModel7 from "./model/users.js"

interface __TeamplayModelManifest {
  "auths": {
    default: typeof __CollectionModel0
  }
  "files": {
    default: typeof __CollectionModel1
  }
  "secrets.*": {
    default: typeof __PathModel2
  }
  "secrets": {
    default: typeof __CollectionModel3
  }
  "testCounts.*": {
    default: typeof __PathModel4
  }
  "testCounts": {
    default: typeof __CollectionModel5
    schema: typeof __Schema6
  }
  "users": {
    default: typeof __CollectionModel7
  }
}

type __TestCountsDoc = FromJsonSchema<typeof __Schema6>
interface __TestCountsFields {
  readonly "value": SignalChild<NonNullable<__TestCountsDoc>["value"], readonly ["testCounts", "*", "value"]>
  readonly "$value": SignalChild<NonNullable<__TestCountsDoc>["value"], readonly ["testCounts", "*", "value"]>
}

declare module "./model/testCounts.schema" {
  export default interface TestCount extends __TestCountsDoc {}
}

declare module 'teamplay' {
  interface TeamplayCollections extends CollectionsFromManifest<__TeamplayModelManifest> {}
  interface TeamplayModels extends PathModelsFromManifest<__TeamplayModelManifest> {}
  interface TeamplaySignalFields {
    "testCounts.*": __TestCountsFields
  }
}
