// This file is generated by TeamPlay. Do not edit manually.
/* eslint-disable */
import { type CollectionsFromManifest, type FromJsonSchema, type PathModelsFromManifest, type PrivateCollectionsFromManifest, type SignalChild } from 'teamplay'
import "@startupjs/auth/plugins/cookieSession.plugin"
import "@startupjs/auth/plugins/jwtSession.plugin"
import "@startupjs/auth/plugins/offlineSession.plugin"
import "@startupjs/auth/plugins/oauth2.plugin"
import "@startupjs-ui/file-input/files.plugin"
import type __Schema0 from "./models/_session/schema.ts"
import type __CollectionModel1 from "./models/files.ts"
import type __PathModel2 from "./models/secrets.[id].ts"
import type __CollectionModel3 from "./models/secrets.ts"
import type __PathModel4 from "./models/testCounts.[id].ts"
import type __CollectionModel5 from "./models/testCounts.ts"
import type __Schema6 from "./models/testCounts.schema.ts"

interface __TeamplayModelManifest {
  "_session": {
    schema: typeof __Schema0
  }
  "files": {
    default: typeof __CollectionModel1
  }
  "secrets.*": {
    default: typeof __PathModel2
  }
  "secrets": {
    default: typeof __CollectionModel3
  }
  "testCounts.*": {
    default: typeof __PathModel4
  }
  "testCounts": {
    default: typeof __CollectionModel5
    schema: typeof __Schema6
  }
}

type __SessionPrivate = FromJsonSchema<typeof __Schema0>
interface __SessionFields {
  readonly "banner": SignalChild<NonNullable<__SessionPrivate>["banner"], readonly ["_session", "banner"]> & __SessionFields_Banner
  readonly "$banner": SignalChild<NonNullable<__SessionPrivate>["banner"], readonly ["_session", "banner"]> & __SessionFields_Banner
  readonly "serverHello": SignalChild<NonNullable<__SessionPrivate>["serverHello"], readonly ["_session", "serverHello"]>
  readonly "$serverHello": SignalChild<NonNullable<__SessionPrivate>["serverHello"], readonly ["_session", "serverHello"]>
}

interface __SessionFields_Banner {
  readonly "visible": SignalChild<NonNullable<NonNullable<__SessionPrivate>["banner"]>["visible"], readonly ["_session", "banner", "visible"]>
  readonly "$visible": SignalChild<NonNullable<NonNullable<__SessionPrivate>["banner"]>["visible"], readonly ["_session", "banner", "visible"]>
}
type __TestCountsDoc = FromJsonSchema<typeof __Schema6>
interface __TestCountsFields {
  readonly "value": SignalChild<NonNullable<__TestCountsDoc>["value"], readonly ["testCounts", "*", "value"]>
  readonly "$value": SignalChild<NonNullable<__TestCountsDoc>["value"], readonly ["testCounts", "*", "value"]>
}

type __TeamplayFeatures = { enableOAuth2: true; accessControl: true }

declare module "./models/_session/schema" {
  export default interface Session extends __SessionPrivate {}
}
declare module "./models/testCounts.schema" {
  export default interface TestCount extends __TestCountsDoc {}
}

declare module 'teamplay' {
  interface TeamplayCollections extends CollectionsFromManifest<__TeamplayModelManifest> {}
  interface TeamplayPrivateCollections extends PrivateCollectionsFromManifest<__TeamplayModelManifest> {}
  interface TeamplayModels extends PathModelsFromManifest<__TeamplayModelManifest> {}
  interface TeamplayFeatures extends __TeamplayFeatures {}
  interface TeamplaySignalFields {
    "_session": __SessionFields
    "testCounts.*": __TestCountsFields
  }
}
