module.exports.ACCESS_ERROR_CODES = {
  ERR_ACCESS_DENY_CREATE: 'ERR_ACCESS_DENY_CREATE',
  ERR_ACCESS_DENY_READ: 'ERR_ACCESS_DENY_READ',
  ERR_ACCESS_DENY_UPDATE: 'ERR_ACCESS_DENY_UPDATE',
  ERR_ACCESS_DENY_DELETE: 'ERR_ACCESS_DENY_DELETE'
}
