exports.include = [
  'react-native-web',
  '@nx-js/observer-util',
  'react-native-dynamic-style-processor',
  '@startupjs/babel-plugin-rn-stylename-to-style/process',
  '@startupjs/babel-plugin-rn-stylename-to-style/dimensions',
  'babel-plugin-react-pug-classnames/classcat',
  'uuid',
  'arraydiff',
  'sharedb/lib/client',
  'rich-text',
  'racer-highway/lib/browser/socket',
  'prop-types',
  'hoist-non-react-statics',
  'path-to-regexp',
  'react-is',
  '@startupjs/ui',
  '@startupjs/app',
  '@startupjs/docs',
  'startupjs',
  'events',
  'startupjs/app',
  'startupjs/init',
  'qs',
  '@mdx-js/react',
  '@fortawesome/fontawesome-svg-core',
  '@fortawesome/react-native-fontawesome',
  '@fortawesome/free-solid-svg-icons',
  'parse-prop-types',
  '@startupjs/ui/config/rootConfig',
  '@startupjs/ui/config/colorToRGBA',
  '@startupjs/ui/config/helpers',
  'randomcolor',
  'react-native-drawer-layout-polyfill'
]

exports.exclude = [
  'react',
  'react-dom',
  'react-native',
  'patch-package',
  'postinstall-postinstall',
  'nconf',
  'prop-types',
  'react-native-code-push',
  'react-native-svg',
  'react-native-collapsible',
  'sharedb'
  // 'events',
  // 'path',
  // 'startupjs',
  // '@startupjs/ui',
  // 'sharedb',
  // 'racer',
  // '@startupjs/docs'
]
