{{ if not .Values.app.cron }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.app.port }}
      targetPort: http
  selector:
    app: {{ .Release.Name }}
{{ end }}