name: E2E tests

on:
  push:
  pull_request:

jobs:
  test-e2e:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: yarn install

    - name: Start app
      run: yarn start &
      env:
        MONGODB_URI: mongodb://localhost:27017
        REDIS_URL: redis://localhost:6379

    - name: Wait for 30 seconds
      run: sleep 30s

    - name: Run tests
      run: yarn wdio
      env:
        MONGODB_URI: mongodb://localhost:27017
        REDIS_URL: redis://localhost:6379
