export const CALLBACK_LINKEDIN_URL = '/auth/linkedin/callback'
export const LINKEDIN_WEB_LOGIN_URL = '/auth/linkedin'
export const CALLBACK_NATIVE_LINKEDIN_URL = CALLBACK_LINKEDIN_URL + '-native'
export const FAILURE_LOGIN_URL = '/login?invalid=1'
export const AUTHORIZATION_URL = 'https://www.linkedin.com/oauth/v2/authorization'
